[package]
name = "todo-list-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.27" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
web-sys = { version = "0.3", features = ["Window", "Storage"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

